# Generated by Django 5.1.3 on 2025-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix', '0003_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
