# Generated by Django 5.1.3 on 2025-01-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix', '0004_mentalhealthresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnxietyTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I feel nervous, anxious, or on edge.')),
                ('q2', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I worry too much about different things.')),
                ('q3', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I have trouble relaxing.')),
                ('q4', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I feel easily annoyed or irritable.')),
                ('q5', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I feel afraid, as if something awful might happen.')),
                ('q6', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='My heart races or pounds without any reason.')),
                ('q7', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I have difficulty concentrating on tasks.')),
                ('q8', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I feel tension in my muscles or body.')),
                ('q9', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I feel faint or lightheaded without reason.')),
                ('q10', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='I avoid situations that make me anxious.')),
                ('total_score', models.IntegerField(default=0, verbose_name='Total Score')),
                ('anxiety_level', models.CharField(default='Not Evaluated', max_length=50, verbose_name='Anxiety Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MentalHealthResource',
        ),
    ]
